### ISSUE TITLE
Sharing intent extras are not passed to activity after pin lock is dismissed

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/PasscodeLock-Android#1]
1. Launch the browser
2. Share a page to WordPress with pin lock enabled
3. Enter your pin code
4. Select 'New Post'
5. Notice that the post editor does not appear

**Comment by daniloercoli** [comment]
I fixed the issue in wp-android here:  https://github.com/wordpress-mobile/WordPress-Android/commit/f07f8f7fbe818633d1ff42f8198eff09b3104f2c It seems to be an issue with the app that tries to restore the latest seen activity on startup.
