### ISSUE TITLE
Material Design

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/PasscodeLock-Android#16]
It'd be nice to update the settings and unlock screen to follow the material design guidelines.

**Comment by tonyr59h** [comment]
[This](https://cldup.com/CQtJbxN6WM.png) is the direction I'm toying with right now. I don't like all the dependencies it introduces with the WordPress-Android project resources but since it's closely related to login/authentication it might be good to use a familiar layout.

**Comment by daniloercoli** [comment]
The new screen is way better :)

Note that this library was developed to be "app free" / "dependencies free" on purpose. To be reused on different apps, other than wp-android.
That's the reason behind its simple layout, and color scheme. If possible we should leave the library with a neutral color schemes, no WP icons, and customized it in the wp-android project.

**Comment by tonyr59h** [comment]
> If possible we should leave the library with a neutral color schemes, no WP icons, and customized it in the wp-android project.

:+1: I'll make sure there's nothing tied to WordPress, we can just override all the layouts in the WordPress project. I'll replace the existing WP logo with something more generic too.

**Comment by roundhill** [comment]
Nice, looking good!

**Comment by tonyr59h** [comment]
I've got a short list to finish before opening a PR. [Here](https://cldup.com/yfbMpQaRjg.png) is the current screen progress.

TODO:
- [x] Ripple animations for numpad touches
- [x] Preference screen styling (still looks Holo-y)
- [x] Don't fill parent with keypad, looks bad on tablet (I want to mimic Google Wallet on this one)

**Comment by tonyr59h** [comment]
Addressed in #17, closing.
