### ISSUE TITLE
Passcode activated and call the camera activity, show lock screen

### ISSUE THREAD

**Issue by coyarzun89** [wordpress-mobile/PasscodeLock-Android#2]
If I set these values:
 public static final int DEFAULT_TIMEOUT = 2
 public static final int EXTENDED_TIMEOUT = 2

And then call the camera activity with onactivityonresult, the lock screen is showed. How can I avoid it?

**Comment by DineshAnandan** [comment]
@coyarzun89 you need setExtendedTimeout by calling the below method

AppLockManager.getInstance().setExtendedTimeout();
