### ISSUE TITLE
Add fingerprint unlocking

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/PasscodeLock-Android#22]
The release of Android 6.0 gives us APIs to interface with fingerprint scanners. It'd be convenient to the user if this was added to the passcode lock screen as an alternative to typing in the four digits.

There are no compatibility libraries to support this, be sure to check the device API level before calling fingerprint APIs.

**Comment by daniloercoli** [comment]
Addressed in https://github.com/wordpress-mobile/PasscodeLock-Android/pull/23

**Comment by matboehmer** [comment]
Can you make this optional? Can I turn fingerprint access off?
