### ISSUE TITLE
How to implement this library to the project?

### ISSUE THREAD

**Issue by ghost** [wordpress-mobile/PasscodeLock-Android#26]
I tried to implement according to guide but I couldn't, how can I do it? Could you tell about details? or Could you implement on a sample app how to do it easily?

**Comment by bparmentier** [comment]
+1. A sample app would be useful (digging through the Wordpress app source code to understand how it's implemented is really not easy).

**Comment by daniloercoli** [comment]
A sample application is now available in the repository. https://github.com/wordpress-mobile/PasscodeLock-Android/issues/34
