### ISSUE TITLE
Interactions Differ between Manage and Unlock

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/PasscodeLock-Android#32]
### Expected

When an incorrect pin is entered, the "Wrong PIN" toast message is displayed and the screen shakes.
### Observed

When an incorrect pin is entered, the "Wrong PIN" toast message is displayed.  While attempting to unlock, the screen shakes also.  While attempting to change or turn off pin lock, the screen does not shake.
### Reproduced

Change PIN
1. Go to User > App > App Settings > Turn PIN lock on.
2. Enter a PIN.
3. Go to User > App > App Settings > Change PIN.
4. Enter an incorrect PIN.

Turn Off PIN Lock
1. Go to User > App > App Settings > Turn PIN lock off.
2. Enter an incorrect PIN.

Unlock
1. Exit the app.
2. Swipe away WordPress from recents app list.
3. Open the WordPress app.
4. Enter an incorrect PIN.
##### Tested

LG G4 on Android 6.0.1 with WordPress 5.4-alpha-9
HTC Nexus 9 on Android 6.0.1 with WordPress 5.4-rc-2
Samsung Galaxy S III on Android 4.4.4 with WordPress 5.3
Samsung Galaxy Tab 3 on Android 4.4.2 with WordPress 5.3

**Comment by theck13** [comment]
See wordpress-mobile/WordPress-Android#4022 for issue in WordPress repository.

**Comment by daniloercoli** [comment]
Addressed in https://github.com/wordpress-mobile/PasscodeLock-Android/pull/33
