### ISSUE TITLE
Improve lock options

### ISSUE THREAD

**Issue by shawnajean** [wordpress-mobile/PasscodeLock-Android#37]
### Suggested behavior

Three settings options for the app to relock:
- Lock app at device screen off
- Lock app after screen of for... minutes
- Enter password once to unlock app

Came in through HS: 112091-h

**Comment by ghost** [comment]
@rachelmcr  @tonyr59h Can U work on this?

**Comment by rachelmcr** [comment]
This project is no longer being maintained. I'm closing this issue to avoid confusion.
