### ISSUE TITLE
PIN input screen can be easily bypassed 

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/PasscodeLock-Android#42]
### Steps to reproduce the behavior
1. Switch PIN lock on
2. Exit the app
3. Wait a few seconds and then reopen the app - you should see the PIN/fingerprint screen
4. Press your phone's back button
5. _Quickly_ reopen the app - you should now be in the app without having to go through the PIN/fingerprint security check

**Tested on Samsung Galaxy S6 Edge, Android 6.0.1

Originally reported on wp-android app here: https://github.com/wordpress-mobile/WordPress-Android/issues/4504

[Samsung-only issue??]

**Comment by dcgavril** [comment]
Easy to reproduce in the Simple note App latest version v1.5.3 on Nexus 5 Android 6.0.1

Set pin, close app, remove the app from the latest apps list, open again the app, pin activity shown, tap on the back button, reopen the app from the latest apps list, voila, you have now access to the notes.

This problem has been raised in a ticket from 2014 :) (just the explication was a bit short)
https://github.com/Automattic/simplenote-android/issues/237
