### ISSUE TITLE
PIN Input Screen Not Shown for Pre-Lollipop Devices

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/PasscodeLock-Android#43]
### Expected

On a pre-Lollipop device (API < 21), enabling the passcode lock by switching on the _Enable lock_ option in Settings displays the PIN input screen.
### Observed

On a pre-Lollipop device (API < 21), nothing is displayed when enabling the passcode lock option.  The Settings screen remains.
### Reproduced
1. Tap **_Settings**_ icon.
2. Tap **_Enable lock**_ option in **_Settings**_.
#### Tested

Nexus 5 on Android 4.4.2 with PasscodeLock Sample 1.0
Samsung Galaxy S III on Android 4.4.4 with PasscodeLock Sample 1.0
Samsung Galaxy Tab 3 on Android 4.4.2 with PasscodeLock Sample 1.0

**Comment by daniloercoli** [comment]
Can repro the issue with version 1.2 of this library in wp-android. Tested on cheap device running Android 4.4.
(I remember it was working fine in version 1.1).

**Comment by daniloercoli** [comment]
Seems that if you click on the "toggle image" the click event is not fired at all. If you click on the label, or somewhere else in the preference row, the click does get fired and the setup screen is shown.
