### ISSUE TITLE
forgot pincode/password ?

### ISSUE THREAD

**Issue by khalid-mahmood** [wordpress-mobile/PasscodeLock-Android#53]
what if password forgot? what to do now?

**Comment by rachelmcr** [comment]
If your site is hosted on WordPress.com, you can reset your password here: 

https://en.wordpress.com/wp-login.php?action=lostpassword

If your site is hosted somewhere else, you can click the "Lost your password?" at the bottom of the login form you use to log into your site in a web browser.

You can find more information about resetting a self-hosted site's password here:

https://codex.wordpress.org/Resetting_Your_Password

If you need any further help, please use the (?) icon on the login screen in the app to contact our app support team.

**Comment by rachelmcr** [comment]
If you know your account password but forgot the PIN code set on the app, please uninstall the app from your device. You can then reinstall the app to open it without entering a PIN code. (You can set up a new PIN code after reinstalling the app, if you would like.)
